language: scala
sudo: false

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - $HOME/.cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "*.lock" -delete
  - find $HOME/.sbt -name "*.lock" -delete

# build with scoverage report and upload to codecov

jobs:
  include:
    - stage: Test (all Scala versions)
      script: sbt +test
    - stage: Coverage (2.12 only)
      script: sbt ++2.12.10 coverage test coverageReport coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
